# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Jenkins in master-agent mode"
description: "Host Jenkins on Oracle Cloud Infrastructure to centralize your build automation and scale your deployment as the needs of your software projects grow."
stackDescription: "Jenkins in master-agent mode"
informationalText: "To connect to the Jenkins UI, copy jenkins_login_url and paste it to your web browser."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid


- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - region
  - jenkins_password

- title: "Optional Configuration"
  visible: true  
  variables:
  - vcn_cidr
  - label_prefix
  - lb_http_port
  - http_port
  - jnlp_port
  - jenkins_version
  - slave_count
  - OsImage
  - bastion_display_name
  - bastion_shape
  - master_shape
  - slave_shape
  - bastion_user
  - bastion_ad_index
  - listener_ca_certificate
  - listener_private_key
  - listener_public_certificate

variables:
  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Region where you deploy your Jenkins"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment OCID"
    description: "Comparment where you deploy your Jenkins"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  jenkins_password:
    type: password
    default: ""
    required: true
    title: "Jenkins admin user password"
    description: "Enter password for Jenkins admin user"

  # Optional Configuration
  vcn_cidr:
    type: string
    required: false
    default: "192.168.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "A single, contiguous IPv4 CIDR block of your choice for the VCN"
  
  label_prefix:
    title: "Subnets' Label Prefix"
    description: "The Label Prefix for Jenkins subnets"
    type: string
    required: false

  lb_http_port:
    title: "Load Balanacer HTTP Port"
    description: "Load Balancer HTTP Port"
    default: 80
    type: number
    required: false

  http_port:
    title: "HTTP Port"
    description: "HTTP Port for Jenkins Server"
    default: 8080
    type: number
    required: false
  
  jnlp_port:
    title: "JNLP Port"
    description: "JNLP Port for Jenkins Server"
    default: 49187
    type: number
    required: false

  jenkins_version:
    title: "Jenkins version"
    description: "Jenkins software version"
    default: "2.249.1"
    type: string
    required: false

  slave_count:
    title: "Number of Jenkins Slave Servers"
    description: "Number of Jenkins Slave Servers"
    default: 2
    type: number
    required: false

  OsImage:
    title: "Operating System Image"
    description: "Operating System Image"
    default: "Oracle-Linux-7.8-2020.09.23-0"
    type: string
    required: false    

  bastion_display_name:
    title: "Name of Bastion Server"
    description: "Name of Bastion Server"
    default: "JenkinsBastion"
    type: string
    required: false

  bastion_shape:
    type: string
    title: "Bastion Server Shape"
    description: "Bastion Server Shape"
    default: "VM.Standard2.4"
    required: false

  master_shape:
    type: string
    title: "Jenkins Master Server Shape"
    description: "Jenkins Master Server Shape"
    default: "VM.Standard2.4"
    required: false

  slave_shape:
    type: string
    title: "Jenkins Slave Server Shape"
    description: "Jenkins Slave Server Shape"
    default: "VM.Standard2.4"
    required: false

  bastion_user:
    type: string
    title: "Bastion Server OS User"
    description: "Bastion Server OS User"
    default: "opc"
    required: false

  bastion_ad_index:
    title: "Index of Availability Domain for Bastion Server"
    description: "Index of Availability Domain for Bastion Server"
    default: 0
    type: number
    required: false

  listener_ca_certificate:
    type: text
    title: "Load Balanacer Listener CA Certificate"
    description: "Load Balanacer Listener CA Certificate"
    required: false
     
  listener_private_key:
    type: text
    title: "Load Balanacer Listener Private Key"
    description: "Load Balanacer Listener Private Key"
    required: false

  listener_public_certificate:
    type: text
    title: "Load Balanacer Listener Public Certificate"
    description: "Load Balanacer Listener Public Certificate"
    required: false


outputs:
  bastion_public_ip:
    title: "Bastion Server Public IP"
    displayText: "Bastion Server Public IP"
    type: copyableString
    visible: true

  jenkins_login_url:
    title: "Jenkins Login URL"
    displayText: "Jenkins Login URL"
    type: string
    visible: true
  
  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: string
    visible: true
  
  master_private_ip:
    title: "Jenkins Master Private IP"
    displayText: "Jenkins Master Private IP"
    type: copyableString
    visible: true

  slave_private_ips:
    title: "Jenkins Slaves Private IPs"
    displayText: "Jenkins Slaves Private IPs"
    type: string
    visible: true

 

