name: 'Build Stack'

on:
  push:
    branches:
      - microdeployment
  pull_request:
    branches:
      - master
env:
  PROJECT_WORKING_DIR: '/build-orm/'

jobs:
  generate-micro-deployment-stack:
    name: 'Generate micro deployment package'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: micro-deployment
    steps:
      - uses: actions/checkout@v1

      - name: 'Terraform version'
        run: terraform --version

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Build Stack'
        run: zip -r jenkins-micro-deployment.zip *.tf *.yaml script