name: 'Build Jenkins ORM Stack'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  PROJECT_WORKING_DIR: '/build-orm/'

jobs:
  generate-oci-arch-jenkins-stack:
      name: 'Generate oci-arch-jenkins ORM Stack'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2              
        - name: 'Generate ORM Stack zip file'
          run: |
            zip -r oci-arch-jenkins-stack-latest.zip *.tf *.tf *.yaml -x provider.tf terraform.tfstate* terraform.tfvars*
            unzip -l oci-arch-jenkins-stack-latest.zip
        - name: 'Publish Release'
          uses: "marvinpinto/action-automatic-releases@v1.1.2"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
          #Artifact will be available for download at: https://github.com/<organization>/<repository>/releases/download/<automatic_release_tag>/<zip file>      
            automatic_release_tag: "orm-deploy"
            prerelease: true
            title: "latest"
            files: |
              ${{ github.workspace }}/oci-arch-jenkins-stack-latest.zip
